spring:
  application:
    name: engagelab-sdk-server

server:
  port: 9876

logging:
  level:
    root: debug

engagelab:
  api:
    # 此为演示数据，请替换成真实数据
    app-key: fcc545917674d6f06c141704
    master-secret: ed2681155310c0ee0b7945cf


